name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test (Elixir ${{ matrix.elixir }}, OTP ${{ matrix.erlang }})
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3"
          elixir-version: "1.14"

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-otp${{ matrix.erlang }}-elixir${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Install and compile dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix do deps.get --only test, deps.compile

      - name: Check for unused dependencies
        run: mix do deps.get, deps.unlock --check-unused
        if: ${{ matrix.lint && steps.cache-deps.outputs.cache-hit != 'true'}}

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Check mix format
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Run tests
        run: mix test
